name: Publish
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  upload_release:
    name: Upload Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Release
        uses: actions/checkout@v2
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACTIONS }}
        with:
          args: 'example-*'


